type Order {
    id:ID!
    user_id:ID!
    product_id:ID!
    quantity:Int!
    total_price:Float!
    order_date:String!
    status:String!
    user:User
    product:Product
}

extend type Query {
    getOrders:[Order]
    getOrderById(id:ID!):Order
}

extend type Mutation {
    createOrder(user_id:ID!,product_id:ID!,quantity:Int!,total_price:Float!,status:String!):Order
    updateOrder(id:ID!,user_id:ID!,product_id:ID!,quantity:Int!,total_price:Float!,status:String!):Order
    deleteOrder(id:ID!):Order
}

extend type User {
    orders:[Order]
}

extend type Product {
    orders:[Order]
}
