type Order {
    id:ID!
    user_id:ID!
    product_id:ID!
    user:User
    product:Product
}

extend type Query {
    getOrders:[Order]
    getOrderById(id:ID!):Order
}

extend type Mutation {
    createOrder(user_id:ID!,product_id:ID!):Order
    updateOrder(id:ID!,user_id:ID!,product_id:ID!):Order
    deleteOrder(id:ID!):Order
}

extend type User {
    orders:[Order]
}

extend type Product {
    orders:[Order]
}
