type Product {
    id:ID!
    name:String!
    price:Float!
    category_id:ID
}

extend type Query {
    getProducts:[Product]
}

extend type Mutation {
    createProduct(name:String!,price:Float!,category_id:ID):Product
}
